### ISSUE TITLE
What the state of this repo ? 

### ISSUE THREAD

**Issue by agjs** [mwils-bp/angular-material-textangular#1]
Hey there. It would be really awesome to continue contributing to this and I haven't tested it yet but I guess it works with latest version of textAngular. Keep rocking this man, we all need it :)...

**Comment by leocaseiro** [comment]
:1:

There's none source code... as well. That would be nice make some improvements.

**Comment by michaelpwilson** [comment]
Sorry this repo is defiantly a mess.

I will have a lot of free time in the coming days, so everything will be updated.

**Comment by marcoziegaus** [comment]
+1, looking forward to the new version.

I've got it running and looking pretty good with some additional CSS, but if it works out of the box, it would be even better. Best would be to make it available via npm and/or bower.

Thanks a lot in advance!

**Comment by michaelpwilson** [comment]
@marcoziegaus is there a preference for the usage of textangular?

I have actually been building a standalone Angular Material component for this, reasoning for doing so was:
1. Textangular supports all the way down to IE8 - this wouldn't be needed for Angular Material, as only browsers with versions n-1; where n is the current browser version.
2. textAngular-rangy.min.js and textAngular-sanitize.min.js wont be needed - same reason as point 1
3. Modifying the existing directive HTML is difficult without changing it to a whole new stucture. I.e we would want to be using Angular components.

There are obviously a few pros to sticking with textAngular, but the approach it takes is very different to Angular Material.

Would like to know people's thoughts on this.

**Comment by michaelpwilson** [comment]
https://github.com/dunkno/mdRichEditor

**Comment by michaelpwilson** [comment]
Still a hell of a lot to do, but it should demonstrate how lightweight the code base will be after dropping textAngular

**Comment by marcoziegaus** [comment]
@dunkno No, there is no preference for textangular.

I was just looking for an easy to use HTML WYSIWYG editor when I came across textangular. As we use Material Design in our projects, I was then looking for a MD version of textangular and found this repo.

So anything that makes it easy for non developers to create HTML formatted text with a fancy material style UI is great for me.

And I totally agree with your reasons to leave textangular behind, it has goals that are totally useless when concentrating on Angular Material.

What you've got over there at mdRichEditor looks really nice!

**Comment by michaelpwilson** [comment]
Great!

I just noticed the code/demo is well behind on what I actually have. So i'll get that updated soon.

I personally think mdRichEditor is the best way to approach getting a WYSIWYG editor for Angular Material.

Will keep you updated @marcoziegaus
