### ISSUE TITLE
Am I missing anything or that what looks like?

### ISSUE THREAD

**Issue by leocaseiro** [mwils-bp/angular-material-textangular#2]
Hi, I'm trying to use this directive, but it seems not designed properly.

I'm using Angular 1.3.15 and Angular Material 0.8.3 as same as your example and just don't look nice.

I have a plunkr you can see: http://plnkr.co/edit/B2qof7KdHuQQRR9BOp72?p=preview

Thanks

**Comment by michaelpwilson** [comment]
I'm not sure what is going on here, but I will be updating this repo with brand new code.

There will also be a live example.
